# Generated by Django 2.1.7 on 2019-05-28 06:24

import Userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=120, unique=True, validators=[Userprofile.validators.validate_userid], verbose_name='Username')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=120, verbose_name='Gender')),
                ('phone', models.BigIntegerField(unique=True, validators=[Userprofile.validators.validate_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('experience', models.IntegerField(default=2, verbose_name='Experience')),
                ('notice_period', models.IntegerField(default=0, verbose_name='Notice Period')),
                ('skill', models.SlugField(choices=[('python', 'Python'), ('java', 'Java')], default='python', verbose_name='Skill')),
                ('source', models.CharField(choices=[('RF', 'Referral'), ('JP', 'Job Portal')], max_length=10, verbose_name='Source')),
                ('interviewer_name_l1', models.CharField(blank=True, max_length=120, null=True, verbose_name='L1 Interviewee Name')),
                ('status_l1', models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('reject', 'Reject')], default='pending', max_length=10, verbose_name='L1 Status')),
                ('rating_l1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='l1 Rating')),
                ('feedback_l1', models.TextField(blank=True, null=True, verbose_name='L1 Feedback')),
                ('level_l1', models.BooleanField(default=False, verbose_name='L1 Level Done')),
                ('interviewer_name_l2', models.CharField(blank=True, max_length=120, null=True, verbose_name='L2 Interviewee Name')),
                ('status_l2', models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('reject', 'Reject')], default='pending', max_length=10, verbose_name='L2 Status')),
                ('rating_l2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='L2 Rating')),
                ('feedback_l2', models.TextField(blank=True, null=True, verbose_name='L2 Feedback')),
                ('level_l2', models.BooleanField(default=False, verbose_name='L2 Level Done')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level Done')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
