# Generated by Django 2.1.7 on 2019-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level_l1',
            field=models.BooleanField(default=True, verbose_name='L1 Level Done'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_l2',
            field=models.BooleanField(default=True, verbose_name='L2 Level Done'),
        ),
    ]
