# Generated by Django 2.1.7 on 2019-05-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_auto_20190601_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=120, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.CharField(choices=[('referral', 'Referral'), ('jop_portal', 'Job Portal')], max_length=10, verbose_name='Source'),
        ),
    ]
