# Generated by Django 2.1.7 on 2019-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_auto_20190601_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
