# Generated by Django 2.1.7 on 2019-06-05 18:04

import Userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0006_userprofile_exam_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expected Salary'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feedback_hr',
            field=models.TextField(blank=True, null=True, verbose_name='HR Feedback'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interviewer_name_hr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='HR Interviewee Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level_hr',
            field=models.BooleanField(default=True, verbose_name='HR Level Done'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_hr',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='HR Rating'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_hr',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('reject', 'Reject')], default='pending', max_length=10, validators=[Userprofile.validators.validate_status_l1], verbose_name='HR Status'),
        ),
    ]
