# Generated by Django 2.1.7 on 2019-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0009_auto_20190606_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level_l1',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=120, verbose_name='L1 Level Done'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_l2',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=120, verbose_name='L2 Level Done'),
        ),
    ]
