# Generated by Django 2.1.7 on 2019-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0010_auto_20190606_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level_hr',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False, verbose_name='HR Level Done'),
        ),
    ]
