# Generated by Django 2.1.7 on 2019-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0011_auto_20190606_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level_hr',
            field=models.BooleanField(default=False, verbose_name='HR Level Done'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating_hr',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='HR Rating'),
        ),
    ]
