# Generated by Django 2.1.7 on 2019-06-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000, verbose_name='Question')),
                ('choice_a', models.CharField(max_length=220, verbose_name='Choice 1')),
                ('choice_b', models.CharField(max_length=220, verbose_name='Choice 2')),
                ('choice_c', models.CharField(max_length=220, verbose_name='Choice 3')),
                ('choice_d', models.CharField(max_length=220, verbose_name='Choice 4')),
                ('answer', models.CharField(choices=[('a', models.CharField(max_length=220, verbose_name='Choice 1')), ('b', models.CharField(max_length=220, verbose_name='Choice 2')), ('c', models.CharField(max_length=220, verbose_name='Choice 3')), ('d', models.CharField(max_length=220, verbose_name='Choice 4'))], max_length=220, verbose_name='Answer')),
            ],
        ),
    ]
