# Generated by Django 2.1.7 on 2019-06-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAnswer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='skill',
            field=models.SlugField(choices=[('python', 'Python'), ('java', 'Java')], default='python', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(choices=[('a', 'Choice A'), ('b', 'Choice B'), ('c', 'Choice C'), ('d', 'Choice D')], max_length=220, verbose_name='Answer'),
        ),
    ]
