# Generated by Django 2.1.7 on 2019-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAnswer', '0003_auto_20190603_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Username')),
                ('question_id', models.SmallIntegerField(blank=True, null=True, verbose_name='Question Id')),
                ('answer_selected', models.CharField(blank=True, choices=[('a', 'Choice A'), ('b', 'Choice B'), ('c', 'Choice C'), ('d', 'Choice D')], max_length=120, null=True, unique=True, verbose_name='Answer')),
            ],
        ),
    ]
