# Generated by Django 2.1.7 on 2019-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAnswer', '0004_userquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer_selected',
            field=models.CharField(blank=True, choices=[('a', 'Choice A'), ('b', 'Choice B'), ('c', 'Choice C'), ('d', 'Choice D')], default='a', max_length=120, null=True, unique=True, verbose_name='Answer'),
        ),
    ]
